// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Report.Repository;

namespace Report.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200907032958_UpdateEntitiesName")]
    partial class UpdateEntitiesName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Report.Data.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2020, 9, 7, 7, 29, 58, 399, DateTimeKind.Local).AddTicks(5094),
                            Status = 3,
                            Title = "Yas Water World"
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2020, 9, 7, 7, 29, 58, 400, DateTimeKind.Local).AddTicks(7948),
                            Status = 5,
                            Title = "Abu Dhabi International Hunting & Equestrian Exhibition"
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2020, 9, 7, 7, 29, 58, 400, DateTimeKind.Local).AddTicks(7996),
                            Status = 6,
                            Title = "Abu Dhabi International Book Fair"
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2020, 9, 7, 7, 29, 58, 400, DateTimeKind.Local).AddTicks(8000),
                            Status = 6,
                            Title = "Kayaking Around The Museum"
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2020, 9, 7, 7, 29, 58, 400, DateTimeKind.Local).AddTicks(8001),
                            Status = 2,
                            Title = "Hypercars: Evolution of Uniqueness"
                        });
                });

            modelBuilder.Entity("Report.Data.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("Individuals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Ahmad",
                            LastName = "Khalid"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Omar",
                            LastName = "Alian"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Mansour",
                            LastName = "Ahmad"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Khalid",
                            LastName = "Mohamed"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Abdullah",
                            LastName = "Naser"
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Mohamed",
                            LastName = "Faisal"
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Mahmoud",
                            LastName = "Omar"
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Amjad",
                            LastName = "Mohamed"
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Hasan",
                            LastName = "Hani"
                        });
                });

            modelBuilder.Entity("Report.Data.Invitation", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("IndividualId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "IndividualId");

                    b.HasIndex("IndividualId");

                    b.ToTable("Invitations");

                    b.HasData(
                        new
                        {
                            EventId = 1,
                            IndividualId = 1
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 2
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 3
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 4
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 5
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 6
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 7
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 8
                        },
                        new
                        {
                            EventId = 1,
                            IndividualId = 9
                        },
                        new
                        {
                            EventId = 2,
                            IndividualId = 5
                        },
                        new
                        {
                            EventId = 2,
                            IndividualId = 6
                        },
                        new
                        {
                            EventId = 2,
                            IndividualId = 7
                        },
                        new
                        {
                            EventId = 2,
                            IndividualId = 8
                        },
                        new
                        {
                            EventId = 2,
                            IndividualId = 9
                        },
                        new
                        {
                            EventId = 3,
                            IndividualId = 3
                        },
                        new
                        {
                            EventId = 3,
                            IndividualId = 4
                        },
                        new
                        {
                            EventId = 3,
                            IndividualId = 5
                        },
                        new
                        {
                            EventId = 3,
                            IndividualId = 6
                        },
                        new
                        {
                            EventId = 3,
                            IndividualId = 7
                        },
                        new
                        {
                            EventId = 4,
                            IndividualId = 1
                        },
                        new
                        {
                            EventId = 4,
                            IndividualId = 4
                        },
                        new
                        {
                            EventId = 4,
                            IndividualId = 9
                        },
                        new
                        {
                            EventId = 5,
                            IndividualId = 2
                        },
                        new
                        {
                            EventId = 5,
                            IndividualId = 3
                        },
                        new
                        {
                            EventId = 5,
                            IndividualId = 8
                        });
                });

            modelBuilder.Entity("Report.Data.Invitation", b =>
                {
                    b.HasOne("Report.Data.Event", "Event")
                        .WithMany("Invitations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report.Data.Individual", "Individual")
                        .WithMany("Invitations")
                        .HasForeignKey("IndividualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
